var age = 25;
age = true;
console.log(age);
age = "hello";
console.log(age);
age = { name: "luigi" };
console.log(age);
var mixed = [];
mixed.push("mario");
mixed.push(false);
console.log(mixed);
var ninja;
console.log(ninja);
